import {
  pgTable,
  serial,
  text,
  integer,
  bigint,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
  check,
} from "drizzle-orm/pg-core";
import { relations, sql } from "drizzle-orm";
import { paymentMethodEnum, paymentStatusEnum } from "./enums";
import { bookings } from "./bookings";

/**
 * PRD §6 — payments, and PRD §8's fee breakdown.
 *
 * Every amount is in kobo. The three components are stored separately, never as
 * a single total, because PRD §8 requires the checkout to show them as separate
 * line items and because they settle differently: the fare belongs to the
 * operator, the convenience fee to ArriveLink, the processing fee to Paystack.
 *
 * Status is advanced only by the Paystack webhook (PRD §9). Nothing the browser
 * sends can move a payment to `success`.
 */
export const payments = pgTable(
  "payments",
  {
    id: serial("id").primaryKey(),
    bookingId: integer("booking_id")
      .notNull()
      .references(() => bookings.id, { onDelete: "cascade" }),

    /** farePerSeat × seatsRequested, in kobo. Operator's share. */
    fareAmount: bigint("fare_amount", { mode: "number" }).notNull(),
    /**
     * Fixed ₦200 = 20000 kobo, identical regardless of payment method
     * (PRD §8, and §10 rules out percentage-based or operator-set fees).
     * Stored per row rather than read from config at display time so a future
     * price change does not rewrite the history of past checkouts.
     */
    convenienceFee: bigint("convenience_fee", { mode: "number" })
      .notNull()
      .default(20000),
    /** Paystack's cut for the chosen method, computed at checkout. */
    processingFee: bigint("processing_fee", { mode: "number" })
      .notNull()
      .default(0),
    /**
     * Generated by Postgres, not by the application — a total that disagrees
     * with its parts is then not representable.
     */
    totalAmount: bigint("total_amount", { mode: "number" }).generatedAlwaysAs(
      sql`fare_amount + convenience_fee + processing_fee`,
    ),

    paymentMethod: paymentMethodEnum("payment_method"),
    status: paymentStatusEnum("status").notNull().default("pending"),

    /** Paystack's transaction reference. Unique — this is the idempotency key. */
    paystackReference: text("paystack_reference"),
    /** Raw webhook body, retained for reconciliation and dispute evidence. */
    paystackPayload: jsonb("paystack_payload"),
    /** Set when the webhook is verified, distinct from when we requested it. */
    paidAt: timestamp("paid_at", { withTimezone: true }),
    failureReason: text("failure_reason"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // One payment per booking. A retry updates the row; it never inserts a second.
    uniqueIndex("payments_booking_unique").on(table.bookingId),
    // Partial: many rows legitimately have no reference until checkout starts.
    uniqueIndex("payments_reference_unique")
      .on(table.paystackReference)
      .where(sql`${table.paystackReference} is not null`),
    index("payments_status_idx").on(table.status),
    check("payments_fare_non_negative", sql`${table.fareAmount} >= 0`),
    check("payments_convenience_non_negative", sql`${table.convenienceFee} >= 0`),
    check("payments_processing_non_negative", sql`${table.processingFee} >= 0`),
  ],
);

export const paymentsRelations = relations(payments, ({ one }) => ({
  booking: one(bookings, {
    fields: [payments.bookingId],
    references: [bookings.id],
  }),
}));

export type Payment = typeof payments.$inferSelect;
export type NewPayment = typeof payments.$inferInsert;
